version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "chopbot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hljt8jn3qide"
s3_prefix = "chopbot"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
