AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  chopbot3000

  SAM Template for chopbot3000

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ReaderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: reader/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 10
      Architectures:
        - x86_64
      Events:
        ReaderSlackApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /search
            Method: post
            RestApiId: !Ref SlackApi


  SlackApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        openapi: "3.0.0"
        info:
          title: Chopbot API
          version: 1.0
        paths:
          /search:
            post:
              x-amazon-apigateway-integration:
                type: "aws"
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ReaderFunction.Arn}/invocations"
                httpMethod: "POST"
                requestParameters:
                  integration.request.header.X-Amz-Invocation-Type: "'Event'" # Tells API Gateway that the event should be dispatched asynchronously
                requestTemplates:
                  application/x-www-form-urlencoded: "{ \"body-json\": $input.json('$') }"
                responses:
                  default:
                    statusCode: 200
                    responseTemplates:
                      text/html: "" # This is the literal text returned to Slack
                passthroughBehavior: "when_no_templates"
                contentHandling: "CONVERT_TO_TEXT"
              responses:
                "200": # Enables return of a blank payload back to Slack, while Lambda continues async
                  description: "200 response"
                  content:
                    text/html:
                      schema:
                        $ref: "#/components/schemas/chopbotTextModel"
              components:
                schemas:
                  chopbotTextModel:
                    type: "object"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ReaderApi:
    Description: "API Gateway endpoint URL for Prod stage for reader function"
    Value: !Sub "https://${SlackApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/search/"
  ReaderFunction:
    Description: "Reader Function ARN"
    Value: !GetAtt ReaderFunction.Arn
  ReaderFunctionIamRole:
    Description: "Implicit IAM Role created for reader function"
    Value: !GetAtt ReaderFunctionRole.Arn
