server:
        protocol: 'https://'
        domain: 'netrunnerdb.com/'
        api_root: 'api/2.0/public/'

rest:
        get_card: 'card/{}'
        get_cards: 'cards'

non_rest:
        get_card_png: 'https://static.nrdbassets.com/v1/large/{}.jpg'

cache:
        max_age_in_seconds: 28800
